### ISSUE TITLE
Dead project?

### ISSUE THREAD

**Issue by michaelh99** [christianbach/tablesorter#130]
Pull requests haven't been merged in more than a year?  Has this project been abandoned?

**Comment by blakeperdue** [comment]
I'd say yes. No updates in 2+ years.

**Comment by maxkoryukov** [comment]
Guys, there is alive fork: https://github.com/Mottie/tablesorter

**Comment by maxkoryukov** [comment]
@michaelh99 , @blakeperdue , there is an alive fork: https://github.com/Mottie/tablesorter

**Usually, issues and PR here are ignored**

**Comment by maxkoryukov** [comment]
issues and PR here are ignored.

**Comment by Mottie** [comment]
I was just made a collaborator for this repository... I'm not sure I want to maintain two separate versions of tablesorter, but I think I'll start merging a few PRs and fix a few of the minor issues.

**Comment by maxkoryukov** [comment]
@Mottie , probably, it is enough to add a warning "MOVED TO <new repo url>" to the description of the repo and to the `README.md`. Though, I am not sure for 100%...

**Comment by Mottie** [comment]
It's not moved. This is still the official version of tablesorter.
