### ISSUE TITLE
Sorting Non-US centric date format.

### ISSUE THREAD

**Issue by kdamball** [christianbach/tablesorter#16]
Trying to sort a table with date format in the form of dd/mm/yyyy. Any solutions? It seems to treat the date as numbers and sorts them that way!

**Comment by sssjorsss** [comment]
There seems to be an issue with dd/mm/yyyy parsing.
change s = s.replace(/(\d{1,2})[\/\-](\d{1,2})[\/\-](\d{2})/, **"$2/$1/$3"**);
into 
s = s.replace(/(\d{1,2})[\/\-](\d{1,2})[\/\-](\d{2})/, **"$2/$1/$3"**);

**Comment by temp** [comment]
Same problem here, did you find a solution for this, @kdamball ?

**Comment by Mottie** [comment]
Set the `dateFormat` option to `'uk'` - [demo](http://jsfiddle.net/Mottie/eY8uH/1591/).

**Comment by kdamball** [comment]
@temp Sadly I had to do a manual date formatting. i.e: take date, parse it and sort the parsed date/data and return new data with the date sorted.

**Comment by temp** [comment]
Thanks for your help!
