### ISSUE TITLE
Using tablesorter with both editable and stickyheaders widgets breaks tab to next cell feature

### ISSUE THREAD

**Issue by DelightedD0D** [christianbach/tablesorter#31]
If you add stickyheaders to a tablesorter instance that is already using the editable widget, you can no longer tab from one editable cell to another.  See http://stackoverflow.com/questions/24947995/tab-to-next-cell-in-tablesorter-with-editable-and-stickeyheaders-widgets 

On line 604 of jquery.tablesorter.widgets.js, I changed....

This check:

if (event.type === 'filterReset') {
    c.$table.find('.' + ts.css.filter).add(wo.filter_$externalFilters).val('');
    ts.filter.searching(table, []);
}...

To read:

if (event.which !== 9){
} 
else if (event.type === 'filterReset') {
    c.$table.find('.' + ts.css.filter).add(wo.filter_$externalFilters).val('');
    ts.filter.searching(table, []);
} .....

So far, this seems to fix the tab feature without breaking any of the sorting functionality.

(To be fair this may have some as yet unknown side effect)

**Comment by Mottie** [comment]
I believe the widgets you are referring to are from my [fork of tablesorter](https://github.com/Mottie/tablesorter), please close this issue and use [one of these methods](https://github.com/Mottie/tablesorter#questions) to get support.
