### ISSUE TITLE
pager plugin does not work in IE11

### ISSUE THREAD

**Issue by smukkekim** [christianbach/tablesorter#54]
The pager plugin hides all rows - even in your own demo page (http://tablesorter.com/docs/example-pager.html)

**Comment by front-a-little** [comment]
While being less perfomant, the "msie-only" code of the clearTableBody method also works for other browsers, you could probably get rid of the whole deprecated browser detection stuff this way.
Tested in FF 34.0.5, Chrome 39.0.2171.99, IE10 and IE11

**Comment by codeconqueror** [comment]
Replace the code in the clearTableBody function as indicated below and it seems to work in all browsers:

CURRENT CODE:
            	if ($.browser.msie) {
                    function empty() {
                        while (this.firstChild)
                        this.removeChild(this.firstChild);
                    }
                    empty.apply(table.tBodies[0]);
                } else {
                    table.tBodies[0].innerHTML = "";
                }



NEW CODE:
		var rowCount = table.rows.length;
               	for (var x = rowCount - 1; x > 0; x--) {
               		table.deleteRow(x);
               	}

**Comment by smukkekim** [comment]
Thanks @codeconqueror - that seems to work.

**Comment by voidpp** [comment]
Or just use https://github.com/gabceb/jquery-browser-plugin to replace $.browser.
codeconqueror's solution breaks the pager functionality for me.

**Comment by smukkekim** [comment]
Thanks @voidpp - as I stated @codeconqueror's solution worked for me, but nice to know of alternatives!

**Comment by Mottie** [comment]
Tablesorter uses jQuery, so you could simplify that code down to this:

```js
this.clearTableBody = function (table) {
    $( table.tBodies[0] ).empty();
}
```
