### ISSUE TITLE
Look at https://github.com/Mottie/tablesorter

### ISSUE THREAD

**Issue by Krinkle** [christianbach/tablesorter#7]
Hi @Mottie, @christianbach,

Just in case you don't know each other, @christianbach recently created a repo for tablesorter here on GitHub. @Mottie did this already in 2011 and a lot of development has happened since. It'd be interesting to see if we can join forces and get a new jquery.tablesorter release soon (last one was in 2008 I think).
- https://github.com/Mottie/tablesorter
- http://mottie.github.io/tablesorter/docs/

**Comment by Chealer** [comment]
@christianbach , do you consider tablesorter 2.0.5 superior to version 2.27.8 of the unofficial tablesorter fork created by @Mottie ? If not, do you consider that tablesorter 2.0.5 is superior for important use cases?

**Comment by Chealer** [comment]
The fork by @Mottie is preparing a new major version called Abelt, which would solve the current naming issue. This will apparently take a while though.
